on:
  push:
  pull_request:

name: check

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: check
        run: wget -q https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf ; rm Complete_thesis.pdf

